CREATE TABLE IF NOT EXISTS user (
    id 			INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email 		VARCHAR(100) NOT NULL,
    username 	VARCHAR(10) NOT NULL,
    fname 		VARCHAR(32) NOT NULL,
    lname		VARCHAR(32) NOT NULL,
    password	VARCHAR(255) NOT NULL,
    age			TINYINT(2) NOT NULL DEFAULT 18,
    gender		TINYINT(1) NOT NULL DEFAULT 0,
    sex_pref	TINYINT(1) NOT NULL DEFAULT 0,
    rate        TINYINT(3) NOT NULL DEFAULT 1,
    biography	VARCHAR(500) NOT NULL DEFAULT "Share your life..",
    tag1		TINYINT(1) NOT NULL DEFAULT 0,
    tag2		TINYINT(1) NOT NULL DEFAULT 0,
    tag3		TINYINT(1) NOT NULL DEFAULT 0,
    tag4		TINYINT(1) NOT NULL DEFAULT 0,
    tag5		TINYINT(1) NOT NULL DEFAULT 0,
    tag6		TINYINT(1) NOT NULL DEFAULT 0,
    tag7		TINYINT(1) NOT NULL DEFAULT 0,
    tag8		TINYINT(1) NOT NULL DEFAULT 0,
    tag9		TINYINT(1) NOT NULL DEFAULT 0,
    avatar		VARCHAR(50) NOT NULL DEFAULT "/template/img/default_avatar.png",
    image1		VARCHAR(50) NOT NULL DEFAULT "/template/img/default_image.png",
    image2		VARCHAR(50) NOT NULL DEFAULT "/template/img/default_image.png",
    image3		VARCHAR(50) NOT NULL DEFAULT "/template/img/default_image.png",
    image4		VARCHAR(50) NOT NULL DEFAULT "/template/img/default_image.png",
    online		TIMESTAMP,
    location_x	REAL NOT NULL DEFAULT 50.4688073,
    location_y  REAL NOT NULL DEFAULT 30.4621631
)