CREATE TABLE IF NOT EXISTS user (
    id 			INT(8) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email 		VARCHAR(100) NOT NULL,
    username 	VARCHAR(10) NOT NULL,
    fname 		VARCHAR(32) NOT NULL,
    lname		VARCHAR(32) NOT NULL,
    password	VARCHAR(255) NOT NULL,
    age			INT(4) NOT NULL DEFAULT 18,
    gender		INT(2) NOT NULL DEFAULT 0,
    sex_pref	INT(2) NOT NULL DEFAULT 0,
    rate        INT(4) NOT NULL DEFAULT 1,
    biography	VARCHAR(500) NOT NULL DEFAULT "",
    tag1		BIT NOT NULL DEFAULT 0,
    tag2		BIT NOT NULL DEFAULT 0,
    tag3		BIT NOT NULL DEFAULT 0,
    tag4		BIT NOT NULL DEFAULT 0,
    tag5		BIT NOT NULL DEFAULT 0,
    tag6		BIT NOT NULL DEFAULT 0,
    tag7		BIT NOT NULL DEFAULT 0,
    tag8		BIT NOT NULL DEFAULT 0,
    tag9		BIT NOT NULL DEFAULT 0,
    avatar		VARCHAR(50) NOT NULL DEFAULT "/template/img/default_avatar.png",
    image1		VARCHAR(50) NOT NULL DEFAULT "/template/img/default_image.png",
    image2		VARCHAR(50) NOT NULL DEFAULT "/template/img/default_image.png",
    image3		VARCHAR(50) NOT NULL DEFAULT "/template/img/default_image.png",
    image4		VARCHAR(50) NOT NULL DEFAULT "/template/img/default_image.png",
    online		TIMESTAMP,
    location_x	REAL NOT NULL DEFAULT 0,
    location_y  REAL NOT NULL DEFAULT 0
)